### PR TITLE
add proper motion for gaia stars

### PR DESCRIPTION
**Pull request by jchiang87**

### CODE REVIEW

**Review by JoanneBogart — COMMENTED** [review]
This looks generally ok but I'm wondering about a couple things.
1. Might stars move in or out of the specified region when proper motion is applied?  If so does it matter?
2. Could there ever be a reason to "move" a GaiaCollection from one mjd to another? If so (or even if not, for consistency), shouldn't mjd or new values for df['epoch'] be saved and queryable?

**Comment by jchiang87** [comment]
> 1. Might stars move in or out of the specified region when proper motion is applied? If so does it matter?

In imSim, there is a configurable buffer around the CCD edges for making the region selection. It has a default value of 100 pixels.  This is meant to capture emission from galaxies whose center is off the CCD, and is more than ample to account for any realistic stellar proper motion relative to their nominal catalog values.

> 2. Could there ever be a reason to "move" a GaiaCollection from one mjd to another? If so (or even if not, for consistency), shouldn't mjd or new values for df['epoch'] be saved and queryable?

We're simulating individual exposures that have a fixed MJD.  I cannot think of any reason we'd need to change the MJD within a simulation.

> shouldn't mjd or new values for df['epoch'] be saved and queryable?

Is there a use case for this?  I can't think of any.

**Comment by JoanneBogart** [comment]
It's not needed for the current use case.  But, if only for debugging, I would like to see mjd saved in the GaiaCollection.

**Review by JoanneBogart — APPROVED** [review]
LGTM

**Review by cwwalter — APPROVED** [review]
Not that familiar with this code base yet. But, the parts I understand LGTM.

**Pull request merged**
